services:
    - docker

before_install:
    - docker build -t suresh2331/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run suresh2331/react-test npm test -- --coverage

after_success:
    - docker build -t suresh2331/multi-client ./client
    - docker build -t suresh2331/multi-nginx ./nginx
    - docker build -t suresh2331/multi-server ./server
    - docker build -t suresh2331/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push suresh2331/multi-client
    - docker push suresh2331/multi-nginx
    - docker push suresh2331/multi-server
    - docker push suresh2331/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-216122847746
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY